In [1]:
from src.plant import Plant, RandomPlantData
from src.planification import Planification
import numpy as np
import time

## Generate random data 

In [2]:
plant_data = RandomPlantData.generate_random_data(
    n_grades=20, n_units=3, intervals_per_day=24, prod_flow_lims=(30, 250),
    man_cost_lims=(10, 60), t_transition_lims=(1, 10), n_not_allowed_max=4, t_min_lims=(1, 20),
    s_min_lims=(5, 60), only_consecutive_p=0.25,
    n_orders=2500, orders_tons_lims=(200, 3000), orders_price_lims=(50, 1000),
    grades_after_10_days_max=10, unique_unit=0)

In [3]:
print(plant_data.keys())

dict_keys(['n_grades', 'n_units', 'intervals_per_day', 'prod_flow', 'man_cost', 't_transition', 't_min', 's_min', 'gamma', 'only_consecutive', 'only_predecessor', 'not_allowed_transitions', 'orders', 'grades_after_10_days', 'unique_unit', 'unique_grades'])


## Generate Plant

In [4]:
plant = Plant.from_dictionary(plant_data)

In [5]:
print(plant.__dict__.keys())

dict_keys(['_n_grades', '_n_units', '_grades', '_intervals_per_day', '_prod_flow', '_man_cost', '_t_transition', '_not_allowed_transitions', '_unique_grades', '_unique_unit', '_s_min', '_t_min', '_gamma', '_only_consecutive', '_only_predecessor', '_single_predecessor', '_grades_after_10_days', 'orders'])


In [6]:
for att, value in plant.__dict__.items():
    if '_' in att:
        print(att, value)

_n_grades 20
_n_units 3
_grades [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
_intervals_per_day 24
_prod_flow [[205.75306991 223.59715656 199.30123536]
 [120.00461762 186.33440581 230.22791065]
 [203.44581864  40.48606603  72.25435122]
 [174.98896393 108.33308159 140.36460324]
 [163.83937319  70.06556998 176.98639779]
 [212.86674212  99.08956632 187.3331967 ]
 [163.06669652 108.60155429  90.0554434 ]
 [127.49515752 232.96920632  97.09074946]
 [179.42342259  99.65202576  99.92812018]
 [175.40011769 192.75348339 230.12648225]
 [169.52036196 140.16099678  65.71990967]
 [232.21751271 241.31619078 126.40139554]
 [ 72.14864817 222.50520028  56.54758164]
 [ 78.25798682  45.61169332  84.40263469]
 [176.80363732 192.43778966 140.78495066]
 [109.67678538 197.36576848 172.40045474]
 [197.29040472  36.42941998 164.78683379]
 [171.56251926 240.08323376 104.42512689]
 [ 93.45118785 248.49021857  85.6832775 ]
 [238.1484333  215.22299067 142.45380453]]
_man_cost [[17.46857014

## Calculate Planification

In [7]:
planification = Planification(
        plant=plant,
        horizon=30 * 24,
        orders_plan={},
        grades_plan={}
    )
t = time.time()
planification.calculate_initial_solution()
elapsed_time = time.time() - t
print(f'elapsed_time: {elapsed_time:.4} seconds')

elapsed_time: 3.094 seconds


In [8]:
print(planification.__dict__.keys())

dict_keys(['plant', 'complete', 'horizon', 'stocks', 'orders_plan', 'grades_plan', 'orders_completed', 'benefits'])


In [9]:
print(f'Benefit: {planification.benefits}')

Benefit: 299628.03506007744


In [10]:
print('Grades plan:')
print('_'*50)
for unit, plan in planification.grades_plan.items():
    print(f'Unit: {unit}')
    print('Plan (grade, start_time): ', plan)
    print('_'*50)

Grades plan:
__________________________________________________
Unit: 0
Plan (grade, start_time):  [(16, 0), (19, 14), (8, 25), (0, 37), (4, 54), (16, 77), (5, 93), (6, 113), (8, 127), (0, 150), (10, 187), (5, 214), (6, 237), (9, 250), (3, 270), (11, 283), (17, 315), (2, 339), (9, 383), (0, 406), (18, 419), (8, 430), (16, 445), (0, 462), (4, 487), (13, 511), (6, 536), (15, 558), (10, 600), (19, 624), (17, 639), (2, 670), (3, 717)]
__________________________________________________
Unit: 1
Plan (grade, start_time):  [(7, 0), (19, 30), (7, 95), (10, 192), (19, 226), (17, 248), (0, 350), (18, 365), (19, 449), (17, 568), (7, 602), (10, 651), (7, 705)]
__________________________________________________
Unit: 2
Plan (grade, start_time):  [(1, 0), (4, 140), (16, 303), (5, 324), (0, 470), (5, 656)]
__________________________________________________


In [11]:
print('Orders plan:')
print('_'*50)
for unit, plan in planification.orders_plan.items():
    print(f'unit: {unit}')
    print('plan (order_id, grade, start_time, end_time, benefit, revenue): ',
          plan[:5])
    print('_'*50)

Orders plan:
__________________________________________________
unit: 0
plan (order_id, grade, start_time, end_time, benefit, revenue):  [('a3cf37d4-fb1f-42be-a6a8-d6067702609a', 16, 0, 1.0260778896740792, 354.23111217952965, 376.6871750159566), ('7eaf4b7b-4ba9-4dad-9544-f99cb2acb384', 16, 1.0260778896740792, 2.269776156211891, 400.9207476352931, 428.1395062733917), ('44c27b49-003c-45be-ab82-27fb70c3165d', 16, 2.269776156211891, 3.57646587812615, 733.7254155305804, 762.3227635470554), ('1b760458-584b-4926-bbd5-ebab477b7e2c', 16, 3.57646587812615, 5.0092416278184295, 722.6305660790131, 753.9873496033305), ('d3955b83-2f0f-481c-bdce-fe31ba4e53f3', 16, 5.0092416278184295, 6.457954949650664, 702.8265001293413, 734.5320828286888)]
__________________________________________________
unit: 1
plan (order_id, grade, start_time, end_time, benefit, revenue):  [('5eaf71e4-396d-47f8-848d-bd136de287c8', 7, 0, 0.8953118778766778, 358.8663074766095, 401.18054363507), ('f8618566-0e9a-4caa-b1b8-f9d081073a